use-grammars = { only = [ "rust", "html", "css", "javascript", "typescript", "toml", "sql", "dockerfile", "python" ] }

[[language]]
name = "rust"

[language.config]
cargo = { buildScripts = { enable = true }, features = "all" }
procMacro = { enable = true }

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'